### ISSUE TITLE
Setup an Appointment with Our Customer

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#11]
A meeting should be arranged to ask our questions about the project to the customer.

**Comment by cburakaygun** [comment]
Since there was a customer meeting on P.S. hours today, I think this Issue can be closed if no additional customer meeting will be done until **Monday** (Feb 19).
@abcdrk

**Comment by abcdrk** [comment]
The arranged PS hour was mentioned to be the Customer Meeting so no additional meeting is arranged.
