### ISSUE TITLE
Create a Wiki Page for Communication Plan 

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#12]
A Wiki page should be created to store our Communication Plan chart.

From Homework#2:
> Your plan should include the following information with the following in each row:
>  * Who will participate
>  * Where  (i.e. department, Doydos, skype, slack, ...)
>  * Purpose (i.e. progress update)
>  * When (i.e. Mondays at 5

**Comment by abcdrk** [comment]
* I recommend putting the communication table on the bottom of the page, 
* and also putting a **Delivery Method** part in the table as it is indicated in the communication plan template. 
* Erasing the communication platforms list or making a table instead of a list is better in terms of design.

**Comment by cburakaygun** [comment]
Currently, the time for the weekly meetings is written as "**Thursday 5pm**".
@ramazanarslan @fakeisback
