### ISSUE TITLE
Create a Manual Page for Commit Messages

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#13]
A template should be determined for commit messages and everyone should try to stick to it while writing a commit message.

**Comment by cburakaygun** [comment]
I added the section [Commit Message Convention](../wiki/Commit-Notes#commit-message-convention).

**Comment by cburakaygun** [comment]
If you have any suggestions about commit message convention (especially about keywords mentioned in [this list](../wiki/Commit-Notes#here-are-the-things-to-remember-while-writing-a-commit-message-for-a-coherent-commit-message-history)), please tell here. Otherwise, I will close this Issue.
@ferhatmelih @jediinthehouse @ramazanarslan @fakeisback @eneskosr @abcdrk @serdarada

**Comment by abcdrk** [comment]
I think it is sufficient 👍
You can close the issue.
