### ISSUE TITLE
Discuss Requirements of the Project

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#16]
We will discuss requirements of the project and create a draft on our **Slack** group. Also, we will prepare questions about the parts that are not clear. Everyone is expected to contribute to that discussion.
Don't forget to tick your name after you have contributed.

- [x] @serdarada  
- [x] @eneskosr 
- [x] @abcdrk 
- [ ] @ferhatmelih 
- [x] @cburakaygun
- [ ] @ramazanarslan 
- [x] @fakeisback 
- [x] @jediinthehouse

**Comment by abcdrk** [comment]
**MY REQUIREMENT LIST**
I have prepared a requirements draft on a wiki page linked [here](https://github.com/abcdrk/try/wiki/Requirements)  , as it is a draft it should be developed.

**MY ADDITIONAL QUESTIONS**
* **Q:** What is the _relation/diference_ between living history posts, memory items an memories?
* **Q:** Will the users be able to _like comments_ ?
* **Q:** Can the others see _who liked_ a post ?
* **Q:** Will there be an _activity log?_  (i.e. @jonathhan liked this _memory_ )
* **Q:** In the explanation part of the _annotations_ what is the difference between _elaborate_ and _meta information_ ?
* **Q:** What factors are important for the _recommendations_ ?

**Comment by cburakaygun** [comment]
Here are my outcomes. I tried to group related concept under separate titles.

_REQ & Q'S_ means _REQUIREMENTS AND QUESTIONS_
An item with a bullet (•) denotes a requirement and an item with *Q:* denotes a related question.

**GENERAL QUESTIONS ABOUT APPLICATION**
**Q:** _Which language(s) will the application support?_
**Q:** _Is a "story" and a "memory" exactly the same concept or are they different from each other? If so, how?_
**Q:** _What is the relation between a post, a story, a memory and a memory item? (e.g. A post has a story, a story has many memory items)_
**Q:** _Will there be a category and/or tag system?_

**REQ & Q'S ABOUT "POST"**
• A Post shall consist of Location, Time & Story
**Q:** _Is "Time" the creation time of the Post or is it related to the Story?_

**REQ & Q'S ABOUT "STORY"**
• A story shall be related to People, Time & Location
**Q:** _Is that all?_
**Q:** _Will there be a single time item (like: around T) or a time period specified by two time items? (like: between T1 and T2)_
**Q:** _What is the precision of Time Format? (e.g. only year & month)_

**REQ & Q'S ABOUT "MEMORY ITEM"**
**Q:** _What exactly is a memory item? Some examples?_
• Users shall be able to create new memory items.
• Users shall be able to search for existing memory items.
• Users shall be able to comment, like and annotate existing items.
**Q:** _Will like count be displayed?_

**REQ & Q'S ABOUT "MEMORY"**
• Memories shall have descriptions.
• Memories shall support images, audio and video.
**Q:** _Are there any file format restrictions? (e.g. only png, mp3 and mp4 are allowed)_
**Q:** _Are there any file size restrictions? (e.g. maximum 5 MB is allowed)_
• Media files should exist on other platforms.
• Memories shall support description of and presentation (on map) of location.
**Q:** _What will be used for map service?_

**REQ & Q'S ABOUT "ANNOTATION"**
• Annotations should support various purposes (stated in pdf).
• W3C Web Annotation Data Model and its Web Annotation Protocol shall be used for storing and retrieving annotations.
• JSON-LD should be used for annotation representation. (As described in W3C documentation)
• The annotations sould be tested to assure validity.
**Q:** _Can customer provide some clarification and suggestion about how to check validity?_

**REQ & Q'S ABOUT "RECOMMENDATION"**
• Application should provide recommendations to the users.
**Q:** _What will recommendations base on? Liking of the users? Activity history of the users?, etc._

**QUESTIONS ABOUT "USERS"**
(Some requirements for users are provided under other titles)
**Q:** _Will the application require users to register to contribute?_*
**Q:** _If so, which information will be required to register? Email, name, etc._
**Q:** _Will login with 3rd party systems (like Facebook and Google) be supported?_
**Q:** _If there will be a registration system, we can say there will be at least 3 User Types: Admin, Member and Guest. Will there be any other User Type?_
**Q:** _What will Guest Users be able to do on application?_
**Q:** _Are Users allowed to annotate stuff created by other users?_
**Q:** _What will Users see on homepage? (Separate for every User Types)_

**QUESTIONS ABOUT "PROFILE" (If there will be Member Users)**
**Q:** _What items will a Profile have? Avatar, bio, real name, username, email, etc._
**Q:** _Are Member Users allowed to update their information on their Profile? If so, are there any restrictions? (Like they cannot update usernames)_
**Q:** _Are Member Users allowed to delete their user accounts? If so what happens to the items created by those Member Users? (Comments, stories, annotations, vs.)_

**REQ & Q'S ABOUT "SEARCH"**
• Users shall be able to search for existing memory items.
**Q:** _Will there be advanced search mechanisms like filtering and sorting search results? If so, we need some details about this from the customer._
**Q:** _According to what will search results be sorted by default? Newest items first?_
