### ISSUE TITLE
Create a Manual Page for the W3C Web Annotation Data Model

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#17]
We are expected to create an **API** that is compliant with the *Web Annotation Protocol* of the W3C *Web Annotation Data Model*.

**Comment by abcdrk** [comment]
This issue is postponed since it is not urgent.

**Comment by cburakaygun** [comment]
Since the assistant will provide us some resources about **W3C Web Annotation Data Model**, this Issue is no longer valid.
