### ISSUE TITLE
Update Requirements Draft to Version 1

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#19]
We have a [Wiki page for requirements](../wiki/Requirements) which is a draft version currently. Today, during meeting 3, some updates (revision id _35a758d_) were done to that page in order to create Version 1 of requirements.

Revise that page and make additional changes if necessary.

**Comment by cburakaygun** [comment]
I revised our draft version of **Requirements** and made some additional changes in order to create _Version 1_. Please have a look at it. If you have something to add or if you think that some parts should be improved, you can tell them under this Issue.
@abcdrk @eneskosr @fakeisback @ferhatmelih @jediinthehouse @ramazanarslan @serdarada

**Comment by cburakaygun** [comment]
Our customer gave a feedback for Verison 1 of the Requirements on Piazza. I will update Version 1 accordingly as soon as possible.

**Comment by abcdrk** [comment]
Can you clear the difference of a member and a user? @cburakaygun

**Comment by cburakaygun** [comment]
@abcdrk
_Member_ refers to the people who have an account on the system. Once a person registers to the system, (s)he takes on the role _member_ no matter if (s)he visits and signs in to the system or not.
For example, a person doesn't have to visit and/or sign in to the system to _have_ a profile.
> Members shall have a profile.

_User_ refers to the members who visit and sign in to the system (active on the system). A person have to sign in to view a profile.
> Users shall be able to view the profile of members.

Furthermore, person roles are not fully separate from each other. Some examples:
* When a person signs in, (s)he takes on the roles _user_, _member_ and _visitor_.
* When a person (member) visits the system (without sign-in), (s)he takes on the roles _guest_, _member_ and _visitor_.
* When a person (not member) visits the system, (s)he takes on the roles _guest_ and _visitor_.
