### ISSUE TITLE
Create a Wiki Page for the Project Plan (Draft)

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#23]
The Project Plan will be discussed under Issue #22 this week. After the discussion, the outcomes need to be collected and documented in a Wiki page.

**Comment by ferhatmelih** [comment]
We did an initial commit about project plan wiki,
we would like other team members to check the content and leave us feedback @eneskosr

**Comment by cburakaygun** [comment]
All I see is a copy-paste of my comment in Issue #22.
I think Wiki page should contain a customized content about our Projet Plan. For example, it can contain a general explanation about the plan and provide external links to materials such as Gantt Chart.
If right now there is no enough stuff to create a proper Wiki page for Project Plan, I think we should make this Issue `status:invalid` and reopen again in the future.
@ferhatmelih @eneskosr

**Comment by eneskosr** [comment]
I have made the status invalid for now, after getting more clear about the project plan this issue will be reopened.
