### ISSUE TITLE
Create Persona and User Story for Guests

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#25]
Create a Persona, some User Stories and Acceptance Criteria for a **guest**. Write your work in a comment under this Issue so that we can give you some feedbacks. Following templates should be followed:

**Persona**
* A Picture (can be ignored here)
* Some Details
* A General Goal

**User Story**
As a guest, `person name` can `what` so that `why`.

**Acceptance Criteria**
* Item 1
* Item 2
* ...

**Comment by fakeisback** [comment]
**PERSONA**

Natalya Siminova from Russia. 
Age :27  , Single.

She is a Yoga trainer ,lives is St.Petersburg.
She is interested in history and historical places of other countries,especially with the gothic architecture.  
She speaks English and a little bit French.
She is an amateur tennis player.
She owns a 2 years old Pug , Gulf.
She is cooperative , likes be a part of the share of information.
She likes to help abandoned animals. She also works volunteerly in PETA.
She searches for different historical places in the platform everyday .

**USER STORY**
As a guest user;

       Natalya Siminova can make searches in the application so that she can see 
       the desired posts.

       Natalya Siminova can benefit from systems' recommendation service so that
       she will be informed about most recent or popular posts.

       Natalya Siminova can sign in and become a registered user so that she will
       be able to share and like posts, make comments and create her own profile.

**ACCEPTANCE CRITERIA**

She wants to be able to connect to the platform whenever she wants.
She doesn't want to see unrelated posts , advertisements etc.
![natalyasiminova1](https://user-images.githubusercontent.com/34097610/36917271-76b385e0-1e67-11e8-8a4f-edef50290132.png)

**Comment by eneskosr** [comment]
In my opinion, guest role is not too restricted to convince people to register to the system. We should discuss about guest role in the next meeting.

**Comment by cburakaygun** [comment]
@eneskosr I am not sure if you are talking about the general "Guest role" in the system or the specific persona above. If you mean the general Guests, our customer says:
> Do not restrict them so much, make the application as open as it can be. Memory comments, likes and annotations may be restricted.

**Comment by eneskosr** [comment]
@cburakaygun I was talking about the general "Guest Role" in the system. The application should not be that open to the guest users. We shall discuss about it tomorrow in the meeting.
