### ISSUE TITLE
Create Mock-up Page Templates for Android

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#30]
Create mock-up page templates for Android until **03.03.2018 22:00**. These templates will be used in mock-ups for user scenarios.

**Comment by abcdrk** [comment]
I have created [mock-up templates for Android](https://ninjamock.com/s/2G6VRRx) you can check and leave comments from here.

**Comment by cburakaygun** [comment]
Nice work.
I have some suggestions:
- Our application alllows for Guest users who can view Homepage and Memory Posts. Since a User is a Guest before singing-in, (s)he should see a Guest Homepage (which contains some links/buttons for sign-in and sign-up) rather than directly seeing the sign-in screen.
- To be consistent with our Requirements (1.3.8.3 and 1.3.8.4), two additinal screens may be created; one for showing the selection of location from a map and another for showing the selection of memory period from a calendar.
