### ISSUE TITLE
Review of Personas, User Stories and Acceptance Criteria

### ISSUE THREAD

**Issue by eneskosr** [bounswe/bounswe2018group7#36]
We have discussed and changed some of the user roles after meeting and PS. I will edit the [wiki page](https://github.com/bounswe/bounswe2018group7/wiki/User-Stories) accordingly.

**Comment by eneskosr** [comment]
I have changed the guest user stories as we have talked in the meeting.

**Comment by cburakaygun** [comment]
@eneskosr There are some remarks about User Stories [here](https://piazza.com/class/jd5vcsniag3zz?cid=64). Currently, User Stories of Guest are **not** in the form `As a <role> I want to <goal/desire> so that <benefit>.`. Also, `ID`s and `names` of stories are missing.

**Comment by eneskosr** [comment]
I have changed the format of the user stories as @cburakaygun mentioned in the previous comment.
