### ISSUE TITLE
Review of Project Plan

### ISSUE THREAD

**Issue by serdarada** [bounswe/bounswe2018group7#38]
Discuss further about the project plan and revise it according to recommendations of the instructor.

**Comment by serdarada** [comment]
We decided to move our project plan to [teamgantt](teamgantt.com). 

[Here](https://prod.teamgantt.com/gantt/schedule/?ids=1083186&public_keys=bounSWE2018group7&zoom=d100&font_size=12&estimated_hours=0&assigned_resources=0&percent_complete=0&documents=0&comments=0&col_width=355&menu_view=1&resource_filter=1&name_in_bar=0&name_next_to_bar=0&resource_names=1#user=&company=&custom=&date_filter=&hide_completed=false&color_filter=) is the link to the project


We have revised the items and I'm going to finish to give the items: assignees, dates and dependencies tonight.

@abcdrk  will set the milestones and deliverables and going to set up the wiki page for the project plan.

**Comment by serdarada** [comment]
[Current pdf of the project plan](https://github.com/bounswe/bounswe2018group7/files/1799815/hi_Story.pdf)

**Comment by cburakaygun** [comment]
It looks good. Some minor issues:
* Under `2. Initialization` there is a task named `Orientation` and it is empty.
* I think `2.3 Research` and `7.1 Git Research` cover the same tasks.

**Comment by serdarada** [comment]
Thanks @cburakaygun 
I made the necessary changes accordingly.

**Comment by abcdrk** [comment]
**The last version of the Project Plan is [here](https://prod.teamgantt.com/gantt/schedule/?ids=1083186&public_keys=bounSWE2018group7&zoom=d100&font_size=12&estimated_hours=0&assigned_resources=0&percent_complete=0&documents=0&comments=0&col_width=355&menu_view=1&resource_filter=1&name_in_bar=0&name_next_to_bar=0&resource_names=1#user=&company=&custom=&date_filter=&hide_completed=false&color_filter=).**
* I have added the dates & assignees. 
* Created milestones. 
* Created the [wiki page](https://github.com/bounswe/bounswe2018group7/wiki/Project-Plan) of the project plan.

**Comment by cburakaygun** [comment]
I think there is no `version 2.0` for Requirements yet. This week's homework was about `Requirements Version 1`.
