### ISSUE TITLE
Customize Labels

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#4]

**Comment by serdarada** [comment]
I believe in the 'meeting #1' we decided that labels will be in the form of 'header:name' to prevent them to become a mess.

Samples: Priority:High ,   Type:Question , Status:In Progress etc... 

This is the link we discussed in the meeting https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63


I see there are labels not created according to what we discussed, please update them accordingly

**Comment by cburakaygun** [comment]
I didn't start yet. :) Just opened the issue.

**Comment by cburakaygun** [comment]
I removed default labels and created new ones as stated in [here](https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63).
