### ISSUE TITLE
Create Diagram Wiki Pages

### ISSUE THREAD

**Issue by abcdrk** [bounswe/bounswe2018group7#45]
Create the Class and Sequence Diagrams' wiki pages, and explain.

**Comment by abcdrk** [comment]
Class Diagram [wiki page](https://github.com/bounswe/bounswe2018group7/wiki/Class-Diagram) is done.
Sequence Diagrams [wiki page](https://github.com/bounswe/bounswe2018group7/wiki/Sequence-Diagrams) is on progress:
  * @cburakaygun 's work is added.

**Comment by serdarada** [comment]
Nice work! @abcdrk 

I added the search and recommendation diagrams to the wiki page.
