### ISSUE TITLE
Create Sequence Diagrams for 'Search' and 'Recommendation'

### ISSUE THREAD

**Issue by serdarada** [bounswe/bounswe2018group7#47]
I will create two sequence diagrams. One for `searching memory posts and users` and one for `recommending posts to user`

**Comment by serdarada** [comment]
Here are the results:

- [Search](https://user-images.githubusercontent.com/14983171/37868018-759a1baa-2fb1-11e8-9878-9e1548e5ab8e.png)

- [Recommendation](https://user-images.githubusercontent.com/14983171/37868019-75d265aa-2fb1-11e8-98de-36f6c03abd6a.png)

**Comment by cburakaygun** [comment]
@serdarada There is no method named `search(keyword: String)` in the `Class Diagram`.

**Comment by serdarada** [comment]
@cburakaygun Okay, i think we need to revise the Class Diagram and include this method.

Because there is ambiguity now which search method will be called when user clicks search button.

In this method the controller can analyze the input string (includes a '@' or '#') then call for the related method.

**Comment by cburakaygun** [comment]
You are right. I am working on it right now. I will update this comment when it is done.

**Comment by serdarada** [comment]
@cburakaygun Thanks, I'm adding those to the diagram
