### ISSUE TITLE
Create Personal Wiki Page

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#5]
It is a good idea to create a personal Wiki page and write some information about ourselves.
Do not forget to link your name with your personel Wiki page in _Group Members_ section in Wiki Sidebar.

Also, tick your name in this comment after you craeted your page.

- [x] @serdarada 
- [x] @eneskosr 
- [x] @abcdrk 
- [x] @ferhatmelih 
- [x] @ramazanarslan 
- [x] @fakeisback 
- [x] @jediinthehouse 
- [x] @cburakaygun

**Comment by cburakaygun** [comment]
I created my personal Wiki page and linked my name in Wiki Sidebar.

**Comment by serdarada** [comment]
I created my personal Wiki page too.
