### ISSUE TITLE
Create Use Case Diagram

### ISSUE THREAD

**Issue by serdarada** [bounswe/bounswe2018group7#51]
We realized we need to draw a Use Case Diagram after discussion at last night.

[Here](https://user-images.githubusercontent.com/14983171/37874482-bb0895d6-3038-11e8-9684-c10d70e778f2.png) is the first draft I drew.

We currently have a single user class in our class diagram, I think we need to discuss how we use it in our sequence diagrams, use cases and use case diagram because there is inconsistency now between them as we have phrases like 'registered user', 'user', 'guest', 'admin', 'visitor'.

**Comment by cburakaygun** [comment]
I think, the nodes in the `Use Case Diagram` doesn't have to correspond to the classes in `Class Diagram`. It just shows the functionalities, which actors can do what in the system. So, maybe 3 separate use case diagrams can be drawn for `Guest`, `User (registered)` and `Admin`. ([This](https://d2slcw3kip6qmk.cloudfront.net/marketing/pages/chart/what-is-a-use-case-diagram-in-UML/UML_use_case_example1-750x731.png) may be useful.)

Currently, in the sequence diagrams, the role that `User` class represents is written on the actor symbol like `Registered User`. I think, it is sufficient, but we may discuss this further.

**Comment by serdarada** [comment]
I updated the diagram according to what we discussed at the online meeting today.

[Here](https://www.draw.io/?lightbox=1&highlight=0000ff&edit=_blank&layers=1&nav=1&title=Use%20Case%20Diagram-2.xml#R7V3bctu6Ff0aP5qD%2B%2BXRcZq0M8k0c9LTnj4qEmNzIomuRB07%2FfqCEkERF6oURZCQY88ktiAKkjbW3tg3LN7g%2B9XLx83s6fFzvkiXNwgsXm7w%2BxuEECBA%2FSpHfh5GOIOHgYdNtjgMNQa%2BZv9Nq8HqdQ%2B7bJFujQuLPF8W2ZM5OM%2FX63ReGGOzzSZ%2FNi%2F7ni%2FNd32aPaTOwNf5bOmO%2FitbFI%2BHUUHBcfyvafbwqN8ZguqZb7P5j4dNvltX73eD8Pf9z%2BHp1UzPVV2%2FfZwt8ufGEP7LDb7f5Hlx%2BGv1cp8uS9lqsR1e96Hl2fpzb9J10eUF%2BPCCP2fLXfXV7%2BZFvqk%2BXPFTC0R9zqfyz91qebgAv%2Fsz3RSZEtmn2bd0%2BSXfZkWWr9Ul3%2FKiyFfqgmX5xLtaIPf5snzd%2B6NIjnPcLbOH8rVF%2FqRGH4vVUj2A6s98VyyzdXpfrzNQg9tik%2F9IG%2FNhLOUH9RXffc%2BWy8b4h%2F1POZ6vC9%2B4K65KguUHS18aQ5X4Pqb5Ki02P9Ul1bO3WIO9wjoT1ePnI3IIPQw9NkAjq8tmFVYf6qmP66X%2BqJbMv3zSWb4bxJZF9Y33CqK%2FNPvPrgSV%2BsoY7H%2BaQ42l1oPlBLfbvWbeqQuUlF72lx5fxB7K33eLVbbW76o%2B7%2BGND8%2Fp4W%2Bbi97CQaNamsLEiQmJdb5OLTRUQ7MKaHO14OnGg8BVtliUb%2FPu%2BTEr0q9Ps3n5ns%2FKzKmxPY7TRQXDNlCV45VJQ2AgkBFggoxDF2QMuCDDA4AMuij7ms4280dnXdTrlIVuk15juYYQCWSmSGA90JCJ8MiE0stlUl7qaJ4tjfXirtyLSrgtZ9ttNj%2BF2aNetiMrfcmKP0r0JbR69G%2Fj0Zd0k6mvUgL7%2FUnkbfPdZp4aW0Ax2zyk1VV6LF0Y26S7Fg1JU5%2Bkq7FNupwV2Z%2Fm5uoTf%2FUOX%2FJsb700EDA1V7peVj3H4ftUL2tud9ZMRJozMdsIH6TgTLSHQ%2F29uyHE3VrfzdblW6l%2Fv29Td4%2BdVnsA6qg9A1gURKbVHm6oT1dFIcTVFI3MWDQFmauKiWXruioKhZbKwXCKQqcEAzQMKaIXgYHEBQZrDbGtup3BYNtfe6IBwcDiAUN3LHAPFiLbQtFQWGDmRHUkGwAL%2FLVgAcWFhcHsArewwMNhQVwjFoQHCzAuLISyCzicZ61j2gYWfkvn%2BWqlADDbJ6Gm9ay55VnXAWdjSWt%2FqrmmbADXWuOrIZz7TTor0nLeMvy4W6%2FzIgYxmXgh1A0%2F6rhvcCG50fv7dJkehKT%2B3e%2FBVEwjIJ3hIR6BBEONG5AZAvmcrvL9h%2FuSbycSi8YNSixnVHbUriECV%2BzGKkftiltOna3QIHK6Sje%2B%2BtDGdl25c9Fs11Z833e7JhIbE9Fwrht23fhP2Q9bY9hsVSrB%2Btu2%2FDW9%2BkBu6Y%2F0ZJchCWSPiZs8%2FGeWPtsyq4srdbklEilq24w9Ngd4NvUhbA5x97B%2BxbCDMC1T3lLfsoT7f0QaV%2BHSTgHXjnVztVCgHYL4doj%2Bq3VIqIPf0tn84Nq%2BxvWS5noJn0UKtl6%2BZEz%2F9ao97Ne4TsJcJ0Y8VjDYOvkSJf3XqRktvsalsmJ1bxQabKncuvox6Io4VKeeSmGwUF0L%2BroiCU%2FiT692LJGEtZlI3Ut0biShPlDCBJWUMYQ4pYKY80KZcM4lFYhKAhkx32W4MIO6ia8RgdK1I0OhZvPzj%2BaDs0rQnl4NGBmuoLX59Y1Qb7EV6wpgzTQgdqZJV%2FixUGNn6PI0iaskSazwo3%2FpAYhEzaYCdAHKjh5mWiCMRcIplgRhhEWdLgyAItdFrpODdTT5D2UOJt3NodWu6s2fgkAuD3W9U1dEn%2FL59E6PLSZv%2BjSYmFzP0BXT53SRzaKSEfY5hqFkxKJxDKFhyxMATXOO9cN%2B3ZnUNeQ0ri2fWO1BdUP8%2BU1nKFEGnCszLaGo%2Bz%2F0tBwnys2kWEVkTHCpO2yGN%2BRsGlfybHegszfgBZGICkTUikec%2FoGuIGKWW0EkD4YTdBU4uQglcdW%2FGECWTeiLEivxg0Uwt1C7o24tR5fB1gv1%2F%2Ftsu9w%2Ftqs683y3T7cZpZ1J9307ISQ8h1GClcaYW4LXpbGIc2bYcygsWM6MRVZ9bzpHFJlWi%2BPL%2FCNfqk1DJBKjBa1auyBWEqx7qg2fSrUJTMZJtTHfscPR8HV%2Bqi3BjJuoAxBehDpPHk4XT2MBHbDaF3QH7dk7JVFet1AvZ4xhQbAwpuVAJgp3ytxzKQin1pu0YE4hY%2FazcdlTecG2%2FcvcIiurCK1zzeqPw5x9Ic3daLLRcBFDP6ByfZKuHVwDHHDkry0G8jXm87h0llgo531jIKJCZYahCpUloAQIM5AWkCeMIymEBJjV0fvw%2BwS%2Fjvjosg5Bvc3GgiHroLjsm4yxj8pCEK6jn09z0qcDUEKftNaIigQ9TnGg90lrCqE1E%2ByWh2n3DS4B2DTHh2IAWFwJnProaA2LvnscshKGEKBwG9mVBTwu3HrDJ64s8XD2yYaPAN3QE8Q8iWid7eDmKS7vybYpqK%2F3hK3wm9Ju1aog8MLuaQLj1NKk4W3beaU6Qz9GtCvdpPKIBv710g7cUpmwxo9NK6IWOcHNn37aRgFKGCJIYs6FpBRZCVda1pWBFBxxJqBEofwE4ga8dVkn7tNOVkFHeDJNoQo6MrJqRTfd82QC9OrHonuWbhHhX%2BOzlU2gpFQiAAQof0lzywTqaSZpWeUoWzWCNWlIN2fwRl15ntpjaR9yrHtsx%2BCuHPakyuEEmF0lH4qW8o2T0kUPtl02Xx%2BAj5SSDeGxRUlKSZmtURAclWwEXkqoG2Sui1qvpiQyTjboFGIkG6qg9uISG8ld91CIqMPPYFO1DrdVQuAGgJO5WN3PMLSAIq6anXAWkvTtSYOIO6AIR8sAge%2B8fOx%2BN4SeoLcOTWLBBBsOExjYcznt1UNi4hrzIH5M6LgkFkwMaCcwdDARrjYLwTXG5xB6%2BgJVbBoXJoLaCRqOshcCN%2FiOiIKPEscLh9yT0QrFplbjLHYSPo4c0Piy7qH6lGsbHSUPn5YRdpIkPt6VYFjSE8dPzcftc2Cwo84NcRywDhbjp%2BZz5NTVNg0jp0kTBL23c0%2B%2BHcK4il2e%2FED%2FUBADux4a0MWDbn4gfoo%2BbvFDqF13xGNIELYe67oOir7W7c1%2F0j0QaV%2Bd43lj7evo23J7vWrejDE4q2pD%2FMbb1z8akT5DFW7F3pj7uq6Us4Fz5rGF4VbqjbvvklKbN3YNt1hXwt7nxvjMxywfLMZHbvzqyiO%2BeMOXPoyMak0it9isWQbPDTikEAlsHi225sUjsfhB5IbxI8JlJBo%2F6SlYyLjAJRyvhfcNZonLpR7uplFQ4yW%2BXvqB6%2BBxdc4r4zhg9oPQhDcZ%2Fcx56UiEftBzD88IGf2EGxL6Mq%2BhiNig526ekZL6eSTly72Gk9SJ28dExOvnion4XMZwYoqm4hyU2q8uWRh2XWMkGrvuNCUROy44w64rN7KV4I%2FIsQj%2B4ES3lgzHTNCCpch8BOxELE6TQveGB8ffYB1PmPcCTLQHyHtR%2FbXAJa56GsQq6rRMT9%2FT4pAAB3odT%2Fz2goubHLpyzj83jSR9twsKVm7z3PQzQto%2FT0ON50RNuGSb5%2B6fY5ipSZj%2F%2FDm6yGjYpFPHl3byrHOKTsITKTpJRyL%2Fg56bp46IsRjY%2F3zpu7olMhLgCeLcKBWQnhSAAqAENDgALdpJ1IcCsBfyTt4VMc5mwcaOMAaRAfTcyXcM7QwZ2fi0LTKeAwjdIn%2FvyEbNlsBW9j6JR2Lvg56bHV87lHxdhNpXjwZKjg2BoH%2FGxTmkC1HAcwET3fd5bCIjrwMA46Lyc5O4sOaG7JG4E%2FZkGE%2FI5wc9N5X%2BdYAWmacpXKD13vuA29MAScAtbpq03tjEfn4YRXYYbkh75cJIdmSHDGSupiGQjMNcxVXQEq6Fwb3dK%2BBE2YxPSPRXp19jZvqzjz%2FVLOejxMcksgxpJ726CtYDpgy4aPCNOas8BNNfyciZwCbVn2nl%2BUhMf%2FBaqf7cCgUEwJOgClbIIRFx0VyYOYiM8I8xnsAm2WbLMp9fakdKd4%2BMf9CcF4FxCP%2BgzjsPdDzi4y49cUTsjSHuclsDgXWXPe6xNKEI4uqw8Y0gsv8C1uXUegFdXy0UPyQkbjLxGk%2FYKhmaQmQ%2B%2FohgB2zJr5Epq9Xd3KHjyske%2BeTrQ%2F1oGK9YWPPCcDkz4ubM2jpxXN2MSQ859ZZmw2lia1OYEZrHLTTh7QQPJTLq5jNO9tEpKe7il6HEY8KOuhmPr8ojuf1b9ApKR90odSrBltPvT7HLifgOPoeT0zQBfBwOhQZJLA4FZKYDYSXdKB3IvTj1LgzwU%2B8yoOtBJ25u8jSxsr71vCFBCX9JUDJu3lvGtIkMGM%2FycA2x9NdoemmJsOKqIv9qBjG64L4VSiZqYuu5s25Lye2ekzM43OEJqxSSxI9Gd0StGxa06F8hFk7uUJxYO1Q4ZLiJh31k8%2FfdxZlRJ2rxrHdrIEMZdppTie9uKfr2vc3ltlelVyzD3PzCVW7dlu70a9Q5wGQqvSNWqUHY7R6d708mLfIiKFgw1WItyZWpVesWOlx2LXci4p48gX2HiX665eZTxtCtgZmcztUszz1uK5BMpVi3GJgnSLh9ZqSrZt1CTBPImYSAKBeu1lCd1pQsEUyqpxgQkPOhShDq4SYvS%2BvHy5XKPH7OF2l5xf8A) is the final diagram

**Comment by serdarada** [comment]
Thanks @cburakaygun , I added `Update a Memory Post` , `Update an Annotation` , `Create a Tag` items and extended the `Search`. I believe we don't have `Tag deletion` , didn't see it on requirements either.
