### ISSUE TITLE
Create Test Cases for Memory Post and Comment Creation

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#53]
**Title:** Memory Post Creation

**Related Requirements:** 1.1.4.2

**Pre-Conditions:**
1. User is signed-in to the system.
2. User is currently on homepage.

| STEPS | ACTIONS | INPUT DATA | EXPECTED OUTPUT | ACTUAL OUTPUT | RESULT |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | Click "New Memory Post" button on homepage header. | - | Memory Post creation page is displayed. | ? | ? |
| 2 | Write a title in "Memory Title" text input. | The Maiden's Tower | - | ? | ? |
| 3 | Write a story in "Memory Story" text input. | According to a legend, an emperor has the tower built and places his daughter there to prevent a prophecy which tells that she will be killed by a venomous snake on her 18th birthday. On the 18th birthday, the emperor brings a basket of exotic fruits to his daughter. An asp which hides among the fruits bits the princess and kills her. | - | ? | ? |
| 4 | Find and select the location of The Maiden's Tower in map. | - | - | ? | ? |
| 5 | Select a time (interval) from calender widget. | 1700 - 1800 | - | ? | ? |
| 6 | Choose an image file from computer. | maidens_tower.png | - | ? | ? |
| 7 | Write comma separated tags in "Tags" text input. | maidens,tower,uskudar | - | ? | ? |
| 8 | Click "Create Memory Post" button. | - | A success message is displayed and user is redirected to the newly created Memory Post page. | ? | ? |

**Post-Conditions:**
1. "maidens", "tower" and "uskudar" tags are saved to database.
2. Memory Location is saved to database.
3. Memory Time is saved to database.
4. Memory Media is saved to database.
5. Memory Post is saved to database.

**Comment by cburakaygun** [comment]
**Title:** Memory Post Creation without Memory Title

**Related Requirements:** 1.1.4.2, 1.3.9.7

**Pre-Conditions:**
1. User is signed-in to the system.
2. User is currently on homepage.

| STEPS | ACTIONS | INPUT DATA | EXPECTED OUTPUT | ACTUAL OUTPUT | RESULT |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | Click "New Memory Post" button on homepage header. | - | Memory Post creation page is displayed. | - | - |
| 2 | Write a story in "Memory Story" text input. | According to a legend, an emperor has the tower built and places his daughter there to prevent a prophecy which tells that she will be killed by a venomous snake on her 18th birthday. On the 18th birthday, the emperor brings a basket of exotic fruits to his daughter. An asp which hides among the fruits bits the princess and kills her. | - | - | - |
| 3 | Find and select the location of The Maiden's Tower in map. | - | - | - | - |
| 4 | Choose an image file from computer. | maidens_tower.png | - | - | - |
| 5 | Write comma separated tags in "Tags" text input. | maidens,tower,uskudar | - | - | - |
| 6 | Click "Create Memory Post" button. | - | An error message (saying that the title cannot be empty) is displayed. | - | - |
| 7 | Write a title in "Memory Title" text input. | The Maiden's Tower | - | - | - |
| 8 | Click "Create Memory Post" button. | - | A success message is displayed and user is redirected to the newly created Memory Post page. | - | - |

**Post-Conditions:**
1. "maidens", "tower" and "uskudar" tags are saved to database.
2. Memory Location is saved to database.
3. Memory Post is saved to database.

**Comment by cburakaygun** [comment]
**Title:** Comment Creation

**Related Requirements:** 1.1.5.1, 1.3.15.1, 1.3.15.2

**Pre-Conditions:**
1. User is signed-in to the system.
2. User is currently on a Memory Post page.

| STEPS | ACTIONS | INPUT DATA | EXPECTED OUTPUT | ACTUAL OUTPUT | RESULT |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | Click "Add Comment" button on comment section. | - | An error message (saying that comment cannot be empty) is displayed. | ? | ? |
| 2 | Write a comment in "Comment" text input. | I miss the old days. You can see photos from old days of İstanbul here: https://in.pinterest.com/marisacm/istanbul-old-days | - | ? | ? |
| 3 | Click "Add Comment" button on comment section. | - | Comment appears at the top of the comment section. Link "https://in.pinterest.com/marisacm/istanbul-old-days" is clickable. | ? | ? |

**Post-Conditions:**
1. Comment is saved to database.
2. "Comment Count" information on Memory Post page is updated (increased by 1).

**Comment by serdarada** [comment]
Good job @cburakaygun !

I think the idea to continue action items after the error message is very good. And I also think maybe we may not have 2 different test cases for successful and unsuccessful memory post creation since the second one seems to encapsulate the former one.

**Comment by cburakaygun** [comment]
The first test case specifies a "full" Memory Post and the second one states that it is possible to create a Memory Post without providing a Memory Time. Hence, I prefer to keep them separate.

**Comment by abcdrk** [comment]
The title is "Memory Post Creation without Memory Title and Memory Time" but you are actually giving a Memory Title in the actions.

I cannot get the point. Is it a part of the test? @cburakaygun

**Comment by cburakaygun** [comment]
Yes, it is a part of the test. Title tells us "_What happens if a user tries to create a Memory Post without providing a Memory Title and a Memory Time?_". Since Memory Title is mandatory, user will have to provide a Memory Title. You can change the title as you wish.
