### ISSUE TITLE
Create Test Cases For Ban A User Scenario

### ISSUE THREAD

**Issue by eneskosr** [bounswe/bounswe2018group7#54]
Here is a test case for a successful Ban A User scenario:

**Related Requirements:** 1.1.8.2.1

**Pre-Conditions:**
1. A user who has behaved inappropriately.

| STEPS | ACTIONS | INPUT DATA | EXPECTED OUTPUT | ACTUAL OUTPUT | RESULT |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | Click the username of the user to go to profile of the user. | - | The profile of the user must be displayed. | ? | ? |
| 2 | Click the "Three-Dot" button to see the options. | - | The options list must be listed. | ? | ? |
| 3 | Click the "Ban User" button. | - | A pop-up message must have been shown informing that the user is banned successfully. | ? | ? |

**Post-Conditions:**
1. "isBanned" field of the user has been changed to TRUE in the database.
2. After being banned, the user cannot log in the system.

Here is a test case 1 for an unsuccessful Ban A User scenario:

**Related Requirements:** 1.1.8.2.1, 1.1.3.3

**Pre-Conditions:**
1. A user who has behaved inappropriately.
2. The user has deleted his/her profile immediately.

| STEPS | ACTIONS | INPUT DATA | EXPECTED OUTPUT | ACTUAL OUTPUT | RESULT |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | Click the username of the user to go to profile of the user. | - | An error message saying that the user is not found. | ? | ? |

**Post-Conditions:**
1. No changes in the system due to some inconsistencies.

Here is a test case 2 for an unsuccessful Ban A User scenario:

**Related Requirements:** 1.1.8.2.1, 1.1.3.3

**Pre-Conditions:**
1. A user who has behaved inappropriately.
2. The user database has been halted for an unknown reason.

| STEPS | ACTIONS | INPUT DATA | EXPECTED OUTPUT | ACTUAL OUTPUT | RESULT |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | Click the username of the user to go to profile of the user. | - | The profile of the user must be displayed. | ?  | ? |
| 2 | Click the "Three-Dot" button to see the options. | - | The options list must be listed. | ? | ? |
| 3 | Click the "Ban User" button. | - | An error message saying that there has been an error while accessing the database.  | ? | ? |

**Post-Conditions:**
1. No changes in the system due to some inconsistencies.

**Comment by cburakaygun** [comment]
I think there is some misunderstanding about `ACTUAL OUTPUT` and `RESULT`. `ACTUAL OUTPUT` refers to the outcome of the **real implementation** of the system and `RESULT` will be set as `PASS` or `FAIL` according to the correspondence between `EXPECTED OUTPUT` and `ACTUAL OUTPUT`. So, both columns must be empty for now.

Furthermore, if we test for a "negative" situation, we **expect** to see a error message. Hence, `EXPECTED OUTPUT` of the first step of unsuccessful scenario should be "An error message".

**Comment by eneskosr** [comment]
In my opinion, `ACTUAL OUTPUT` should say what has been shown to the user. `RESULT` should say if it is a `PASS` or `FAIL` with the reason behind it. 
Also, I **should not** expect different output for the **same** `ACTIONS`. Because I cannot have any` INPUT DATA` for this scenario, I believe that I should not change the `EXPECTED OUTPUT`. What I mean is I cannot guess **beforehand** if it is a `PASS` or `FAIL` for this scenario, this is why I have done it like this.

**Comment by eneskosr** [comment]
@cburakaygun I got your point and made the changes accordingly. If there is not anything you want me to add on, I am closing the issue.

**Comment by serdarada** [comment]
For the `unsuccessful Ban A User` case, to apply second and third steps user's profile must be displayed. But according to `expected output` of step 1, the profile shouldn't be displayed.

I think there should be only 1 step

**Comment by eneskosr** [comment]
I have behaved them as distinct events. Precondition 2 and 3 are mutually exclusive. If user has deleted his own profile, show this error. If the database is inaccessible, show this error.

**Comment by serdarada** [comment]
I think those 2 should be seperate test cases then

**Comment by eneskosr** [comment]
@serdarada I have made seperate test cases.

**Comment by cburakaygun** [comment]
Current state of the test cases seems okay to me.

**Comment by eneskosr** [comment]
@abcdrk Sorry for the inconvenience, this is the latest version for now.
