### ISSUE TITLE
Create a Test Case for Signup and Signin 

### ISSUE THREAD

**Issue by ferhatmelih** [bounswe/bounswe2018group7#55]

**Comment by serdarada** [comment]
For the `Sign-Up (FAIL)` case, In step 5, it is not clear where the guest presses/types the email, if it is the email field in the sign-up page it is already filled, if there is another window created after he presses the sign-up button, it should be specified.

I think after the message `you are already a member...` he should click `forgot my password` button, then a new window/pop-up must be displayed, then user types his email, then he clicks to `reset password` button. Finally a message saying `Instructions to reset...` must be displayed.


A little remark about the use of the issue system. 
 * We create the issue
 * We post our work
*  We discuss what can be changed or added... to the tork under this isse and revise the work accordingly.
After this steps the work goes into wiki page.

Please be more careful about this in the next time.

Also, we discussed at this week's meeting the part that `adding test cases to wiki page` will be applied by @abcdrk only.

**Comment by ferhatmelih** [comment]
Thank you @serdarada for the feedback.
About the remark you make about not editing the wiki page;
It is not mentioned in the meeting notes! 
Although I attended the meeting from beginning to the end it is likely for one to miss such a detail in a meeting longer than an hour, especially when it is done late at night! Also, any member who missed the meeting would miss this remark.
So please remind such point to the whole group through Slack messaging, rather than writing this under the issue. And make sure that this is included in the meeting notes, if you think this is such an absolutely important point!
Please be more considerate next time!
