### ISSUE TITLE
Create Test Cases for Like and Annotate

### ISSUE THREAD

**Issue by jediinthehouse** [bounswe/bounswe2018group7#56]

**Comment by jediinthehouse** [comment]
**Test ID:** #

**Title:** Annotation(Success)

**Related Requirements:** 1.1.6 

**Designed By:** Neval Tüllük

**Pre-Conditions:**
1. User is signed-in.
2. User is on the homepage.

| STEPS | ACTIONS | INPUT DATA | EXPECTED OUTPUT | ACTUAL OUTPUT | RESULT |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | User clicks add annotate button| - | - | ? | ? |
| 2 | User writes some text into annotation | "Hey, my mom used to live here, here are some photos" | - | ? | ? |
| 3 | User clicks adds some images into annotation  | sariyer1960.jpeg , sarıyerevleri.jpeg | - | ? | ? |
| 4 | User clicks the make annotation button| - | Annotation is displayed for the related memory post | ? | ? |


**Post-Conditions:**
1. Users annotation saved to the database

***
**Test ID:** #

**Title:** Annotation(Failure)

**Related Requirements:** 1.1.6 

**Designed By:** Neval Tüllük

**Pre-Conditions:**
1. User is signed-in.
2. User is on the homepage.

| STEPS | ACTIONS | INPUT DATA | EXPECTED OUTPUT | ACTUAL OUTPUT | RESULT |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | User clicks add annotate button| - | - | ? | ? |
| 4 | User clicks the make annotation button| - | Error message: "annotation is not valid" , appears on the screen| ? | ? |


**Post-Conditions:**

***

**Test ID:** #

**Title:** Like (success)

**Related Requirements:** 1.1.4.5 

**Designed By:** Neval Tüllük

**Pre-Conditions:**
1. User is signed-in.
2. User is on the homepage.

| STEPS | ACTIONS | INPUT DATA | EXPECTED OUTPUT | ACTUAL OUTPUT | RESULT |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | User clicks the like button| - | Memory post succesfully liked by the user | ? | ? |

**Post-Conditions:**
1. User's like saved to database

***

**Title:** Like (failure)

**Related Requirements:** 1.1.4.5 

**Designed By:** Neval Tüllük

**Pre-Conditions:**
1. User is signed-in.
2. User is on the homepage.
3. User has no internet connection

| STEPS | ACTIONS | INPUT DATA | EXPECTED OUTPUT | ACTUAL OUTPUT | RESULT |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | User clicks the like button | - | Error message saying "internet connection cannot be found, please be sure you have connection and try again" appears on the screen | ? | ? |

**Post-Conditions:**

**Comment by cburakaygun** [comment]
* For the `annotation` cases, I think the user should navigate to (or start at) a Memory Post to create an annotation. I mean, being able to annotate a Memory Post on homepage does not seem right to me.

* I think, `Like (failure)` case is not necessary since the specified error (no internet) is not a failure of our system. Also, if there is no internet, how does the system show the user an error message like this?

**Comment by serdarada** [comment]
For the `Like (Success)` case I think there must be a Post-Condition such as `Like Count attribute of the Memory post incremented by 1`
