### ISSUE TITLE
Create Test Cases for "Delete a Comment" and "Edit Memory Post"

### ISSUE THREAD

**Issue by abcdrk** [bounswe/bounswe2018group7#58]
**Test ID:** #

**Title:** Delete a Comment

**Related Requirements:** 1.1.5.2 , 1.3.9.5

**Designed By:** Dilruba Reyyan Kılıç

**Pre-Conditions:**
1. User is signed-in to the system.
2. User is currently on a Memory Post page.
3. There exists a comment.

| STEPS | ACTIONS | INPUT DATA | EXPECTED OUTPUT | ACTUAL OUTPUT | RESULT |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | User clicks on the "Delete Comment" button | - | The Comment is deleted from the viewed Memory Post | ? | ? |

**Post-Conditions:**
1. Comment is removed from the Database.
2. Memory Post's comment count is be decreased by 1.

***
**Test ID:** #
**Title:** Edit Post (Successful)

**Related Requirements:** 1.1.4.3.1

**Designed By:** Dilruba Reyyan Kılıç

**Pre-Conditions:**
1. User is signed-in to the system.
2. User is currently on a Memory Post.

| STEPS | ACTIONS | INPUT DATA | EXPECTED OUTPUT | ACTUAL OUTPUT | RESULT |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | Clicks "Edit Memory Post" button. | - | Memory Post edit page is displayed. | ? | ? |
| 2 | Clicks on the title field to change the input. | - | Cursor appears on the title field.  | ? | ? |
| 3 | Inserts text to change the title.| The Galata Tower | The Galata Tower appears on the title field on the edit page. | ? | ? | 
| 3 | Click "Save Edits" button. | - | The title of the Memory Post is changed to "The Galata Tower" | ? | ? |

**Post-Conditions:**

1. Memory Title of the Memory Post  is changed on the Database.

*** 
**Test ID:** #
**Title:** Edit Post (Failed)

**Related Requirements:** 1.1.4.3.1 , 1.3.9.7

**Designed By:** Dilruba Reyyan Kılıç

**Pre-Conditions:**
1. User is signed-in to the system.
2. User is currently on a Memory Post.

| STEPS | ACTIONS | INPUT DATA | EXPECTED OUTPUT | ACTUAL OUTPUT | RESULT |
| :---: | :---: | :---: | :---: | :---: | :---: |
| 1 | Clicks "Edit Memory Post" button. | - | Memory Post edit page is displayed. | ? | ? |
| 2 | Clicks on the title field to change the input. | - | Cursor appears on the title field. | ? | ? |
| 3 | Deletes the title. |  | The title field is empty. | ? | ? |
| 4 | Click "Save Edits" button. | - | An "A Memory Post must have a Title" Error appears.  | ? | ? |

**Post-Conditions:**

1. Memory Post is not changed.

***

**Comment by abcdrk** [comment]
Since it is not very clear, I assumed that a Memory Post **MUST** have a Memory Title.

**Comment by serdarada** [comment]
Following item is from our requirements

1.3.9.7 Memory posts shall be required to have a memory title.

You can add it to `related requirements` too.

**Comment by abcdrk** [comment]
Thanks, you helped a lot! @serdarada
