### ISSUE TITLE
Request for links to Project Plan, Requirements and Annotation Related Scenarios

### ISSUE THREAD

**Issue by abcdrk** [bounswe/bounswe2018group7#69]
[Link](https://github.com/bounswe/bounswe2018group7/wiki/Requirements) for the requirements.
[Link](https://github.com/bounswe/bounswe2018group7/wiki/Project-Plan) for the Project Plan.

Each annotation sceanario will be added on [this page](https://github.com/bounswe/bounswe2018group7/wiki/Annotation-Scenarios) by the student who gave the example at class. @cburakaygun @ramazanarslan @abcdrk @mfbalin

**Comment by cburakaygun** [comment]
My part is done.

**Comment by mfbalin** [comment]
My part is also done

**Comment by abcdrk** [comment]
The last annotation scenario is added and the issue is closed with 4 annotation scenarios.
