### ISSUE TITLE
Create a Wiki Page for Best Github Repos (Homework#1)

### ISSUE THREAD

**Issue by ramazanarslan** [bounswe/bounswe2018group7#8]
Everyone should write their favourite GitHub repos (with reasons) in a comment under this Issue. Then, @eneskosr will create a Wiki Page about it.

**Comment by ramazanarslan** [comment]
[Lottie for Android, iOS, React Native, and Web](https://github.com/airbnb/lottie-android)

I really liked this repo. Because It looks very beautiful visually. Its prepared in detail. You can easily understand that how to download and use.

Lottie is a mobile library for Android and iOS that parses Adobe After Effects animations exported as json with Bodymovin and renders them natively on mobile!

![example1](https://user-images.githubusercontent.com/31334024/36064244-39e497b8-0e99-11e8-8274-5a522e3dd77b.gif)

**Comment by serdarada** [comment]
[Picocli](https://github.com/remkop/picocli)
_Picocli is a one-file framework for creating Java command line applications with almost zero code. Supports a variety of command line syntax styles including POSIX, GNU, MS-DOS and more._ 

I liked how they used issues on this repo.


[Angular](https://github.com/angular/angular-cli  ) 
_Angular is designed for develop across all platforms by learn one way to build applications and reuse your code and abilities to build apps for any deployment target. For web, mobile web, native mobile and native desktop._ 

I liked their organization on GitHub and the way they documented using wiki system.

**Comment by eneskosr** [comment]
[Carbon](https://github.com/dawnlabs/carbon)
First repo I have found is Carbon. It is a very simple but useful tool for code sharers. The reason why I liked this repo is its purpose can be written in a few words “Create and share beautiful images of your source code”. 

[Detectron](https://github.com/facebookresearch/Detectron)
The second repo I have liked is Detectron. It is an image processing project that detects objects in the picture and highlights them with the labels. It uses convolutional neural networks and deep learning algorithms which are very popular recently.

**Comment by abcdrk** [comment]
[Homebrew](https://github.com/Homebrew/brew)

Homebrew is a lifesaver for MacOS environment. But the feature that i liked in this repository is far more cooler than the benefit of the tool. The step to step explanation! The installation is explained in the best way with headings for each problem defined. 
Also the states are explained in good images like: 
[![Travis](https://img.shields.io/travis/Homebrew/brew.svg)](https://travis-ci.org/Homebrew/brew)
[![Codecov](https://img.shields.io/codecov/c/github/Homebrew/brew.svg)](https://codecov.io/gh/Homebrew/brew)
All issues have links to guide to a better solution material so it doesn't overwhelm the visitor with unwanted issue explanations on the homepage.
The sponsors are mentioned in the end of the page, so we can see a blink of some professionalism. 
( Not a surprise for such a successful project though 👍 )

**Comment by jediinthehouse** [comment]
## [angular-medellin/meetup](https://github.com/angular-medellin/meetup)

> _This repo has a beautiful homepage._

###  The things I like:
* the badges they used for stats 

<a> <img src="https://img.shields.io/badge/👫-+1000_miembros-1d2935.svg?style=flat" alt="Contribuyentes"> </a><a><img src="https://img.shields.io/badge/👫-25_contribuyentes-1d2935.svg?style=flat" alt="Contribuyentes"> </a> <a> <img src="https://img.shields.io/badge/💰-1_patrocinador-1d2935.svg?style=flat" alt="Speakers" ></a><a>  <img src="https://img.shields.io/badge/🕴🕴-2_organizadores-1d2935.svg?style=flat" alt="Speakers"> </a> 
* well placed emoticons
* Contributor's photos as well not just the name. Great visualization.

## [php-censor](https://github.com/php-censor/php-censor)

> _PHP Censor is an open source self-hosted continuous integration server for PHP projects._

### The things i liked the most about this repo : 
* Project logo
* Lots of screenshots
* The contents part that you can jump to the point you are insterested in easily
* Step-by-step installing and upgrading instructions

**Comment by ferhatmelih** [comment]
[Web Developer Roadmap ](https://github.com/kamranahmedse/developer-roadmap)
I find this repo to be very graphic and simple to understand. It is not stuffed with many many files, everything is simply grouped together. 
<img width="954" alt="screen shot 2018-02-11 at 4 20 24 pm" src="https://user-images.githubusercontent.com/20578853/36073806-8e4e36a2-0f47-11e8-8580-26afd8f0b881.png">


[Autonomous Car Documentation](https://github.com/takeitallsource/awesome-autonomous-vehicles)
This repo is a great source for anyone interested in the topic of autonomous cars. It simple puts together every resource that is available on the internet together .
<img width="126" alt="screen shot 2018-02-11 at 4 20 37 pm" src="https://user-images.githubusercontent.com/20578853/36073803-8914b490-0f47-11e8-9752-d4041f88a957.png">

**Comment by fakeisback** [comment]
[Awesome-Cheatsheets](https://github.com/LeCoupa/awesome-cheatsheets) 
In this repo you'll find awesome cheatsheets for popular programming languages, frameworks and development tools. They include everything you should know in one single file. I really find it useful to have some cheatsheets down while working on something important. This repository will help you while trying to improve your skills on a programming language , framework etc. Most of the content is coming from official documentations by the way.



[Carbon](https://github.com/dawnlabs/carbon)  
Here's the Introduction part:
You know all of those code screenshots you see on Twitter? Though the code's usually impressive, we saw room for improvement in the aesthetic department. Carbon makes it easy to create and share beautiful images of your source code. So what are you waiting for? Go impress all of your followers with your newfound design prowess.

While working on codes , sometimes it can be a big deal to understand a code that one of your friends has written. To be able not to get lost in the loops and lines , you can use Carbon to share your code.
