### ISSUE TITLE
Integration API to React Problem

### ISSUE THREAD

**Issue by ramazanarslan** [bounswe/bounswe2018group7#82]
`(Failed to load https://history-backend.herokuapp.com/auth/login/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.)`
I take this error. 

So you should add 
Install from pip:
`pip install django-cors-headers
`

and then add it to your installed apps:
`INSTALLED_APPS = (
    ...
    'corsheaders',
    ...
)`

You will also need to add a middleware class to listen in on responses:

`MIDDLEWARE = [  # Or MIDDLEWARE_CLASSES on Django < 1.10
    ...
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    ...
]`

in detail [https://github.com/ottoyiu/django-cors-headers](https://github.com/ottoyiu/django-cors-headers)

**Comment by cburakaygun** [comment]
Hello @ramazanarslan 

I am not sure, but I think you are making login request to `auth/login`. However, out API endpoint for login is `api/v1/signin`. Can you check that?

**Comment by cburakaygun** [comment]
I see. I updated the server. Can you check it now?

**Comment by ramazanarslan** [comment]
Thanks. I checked. It works 👏
