### ISSUE TITLE
Revise Project Requirements

### ISSUE THREAD

**Issue by cburakaygun** [bounswe/bounswe2018group7#83]
Hello team,

As you know, we need to revise our Requirements. Serdar, Fatih and I did a quick revision today. We updated some parts and attached some notes to some other parts to be updated. (Hence, the current version of the Requirements Wiki page is not in the proper format now.) I will update the Wiki page and do the remaining revisions according to the email of our customer.

I will inform you once I update the Wiki page. Then, we can discuss on here to make further revisions.

**Comment by cburakaygun** [comment]
Hello all.

I updated our [Requirements](https://github.com/bounswe/bounswe2018group7/wiki/Requirements). If you have any suggestions, we can discuss them here. Note that some "requirements" come by definition, e.g.
> Username: A sequence of **at least 2, at most 32 alphanumeric** characters that **uniquely** identifies an account of the system.

We should keep requirements as plain as possible. Also, I think we should focus especially on the definitions of `Memory-Time` and `Memory-Location`.

**Comment by mfbalin** [comment]
I went over it and changed some parts. They were mostly technical changes such as reorganizing etc.

**Comment by cburakaygun** [comment]
Hello again.

I revised the Requirements again according to the feedback of our customer. Basic changes I made are as follows:
- Email confirmation on signup was added
- Authenticating via Facebook was removed
- Wording of the requirement `1.1.5.2` was updated to contain more detail about the annotation structure
- Definition of `recommendation` was updated to state that similar memory-tags will also be considered

All of the changes can be seen [here](https://github.com/bounswe/bounswe2018group7/wiki/Requirements/_compare/585328287ea83942d2966d65c9fced94928c0633...d9ac5579e7f328fb816dc593e943f076319a94ac).

Can you check if I missed anything?
