### ISSUE TITLE
Create a Doodle for Determining a Suitable Slot for Regular Team Meetings

### ISSUE THREAD

**Issue by ramazanarslan** [bounswe/bounswe2018group7#9]

**Comment by cburakaygun** [comment]
Link is [here](https://doodle.com/poll/4w5yrapiyps7wykc).
I think this issue should be closed **after** everyone participated in the Doodle.

**Comment by cburakaygun** [comment]
Everyone participated in the Doodle.
It seems that the only time slot suitable for everyone is **Monday 15.00 - 16.00**.
