### ISSUE TITLE
Filling the Milestone 1 Report

### ISSUE THREAD

**Issue by eneskosr** [bounswe/bounswe2018group7#99]
### Hi Team,

**[Here](https://github.com/bounswe/bounswe2018group7/wiki/Milestone-1-Report)** you can reach the milestone 1 report. I need some information from all of you. 

Could you please fill parts related directly to you or your team:
- See [list of the the deliverables](https://github.com/bounswe/bounswe2018group7/wiki/Milestone-1-Report#list-and-status-of-the-deliverables) and fill out the cell related to the teams. One member from each team is adequate.
- And summarize your coding work in [this table](https://github.com/bounswe/bounswe2018group7/wiki/Milestone-1-Report#coding-work).

I have written the sections below so far. If you want to add/modify anything, please feel free to edit.
- Executive Summary
- List and Status of the Deliverables
- Coding Work
- Requirements
- Project plan 

These are the missing parts:
- **_Design_**
- **_The Code Structure and Group Process_**
- **_Evaluation of Tools and Managing the Project._**

Best

**Comment by cburakaygun** [comment]
I updated `Project Plan` part according to our current [Project Plan](https://github.com/bounswe/bounswe2018group7/wiki/Project-Plan).
